version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw

  certbot:
    build: 
      context: certbot
      args:
        - DOMAIN=$DOMAIN
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot


# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  default:
    name: iot-backend
