services:
  # mqtt5 eclipse-mosquitto
  # mosquitto:
  #   image: eclipse-mosquitto
  #   container_name: mosquitto
  #   ports:
  #     - "1883:1883" #default mqtt port
  #   volumes:
  #     - ./certbot/data:/etc/letsencrypt
  #     - ./mosquitto/config:/mosquitto/config:rw
  #     - ./mosquitto/data:/mosquitto/data:rw
  #     - ./mosquitto/log:/mosquitto/log:rw

  #   networks:
  #     - iotcore

  certbot:
    image: euikook/certbot-iotcore
    build: 
      context: certbot
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    command: 
    environment:
      - DOMAIN=$DOMAIN

    #depends_on: [nginx]

  nginx:
    image: euikook/nginx-iotcore
    build:
      context: nginx
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - DOMAIN=$DOMAIN


    #depends_on: 
    #- mosquitto

networks:
  default:
    name: iotcore
